#ifndef __TableLanguagesfontnewHeader_h__
#define __TableLanguagesfontnewHeader_h__
/* È«²¿ */
const int LANGUAGESFONTNEW_TABLE_BAR_LABEL_0 = 0;
/*  */
const int LANGUAGESFONTNEW_TABLE_BAR_LABEL_1 = 1;
/*  */
const int LANGUAGESFONTNEW_TABLE_BAR_LABEL_2 = 2;
/*  */
const int LANGUAGESFONTNEW_NAVIGATION_BAR_ITEM_NAME_0 = 3;
/*  */
const int LANGUAGESFONTNEW_NAVIGATION_BAR_ITEM_NAME_1 = 4;
/*  */
const int LANGUAGESFONTNEW_NAVIGATION_BAR_ITEM_NAME_2 = 5;
/*  */
const int LANGUAGESFONTNEW_NAVIGATION_BAR_ITEM_NAME_3 = 6;
/*  */
const int LANGUAGESFONTNEW_SEARCH_CONTENT_TEXT = 7;
/*  */
const int LANGUAGESFONTNEW_LOGIN = 8;
/*  */
const int LANGUAGESFONTNEW_LOGOUT = 9;
/*  */
const int LANGUAGESFONTNEW_ACCOUNT = 10;
/*  */
const int LANGUAGESFONTNEW_PASSWORD = 11;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_01 = 12;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_02 = 13;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_03 = 14;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_04 = 15;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_05 = 16;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_06 = 17;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_07 = 18;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_08 = 19;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_09 = 20;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_10 = 21;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_11 = 22;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_12 = 23;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_13 = 24;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_14 = 25;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_15 = 26;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_16 = 27;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_17 = 28;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_18 = 29;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_19 = 30;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_20 = 31;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_21 = 32;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_22 = 33;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_23 = 34;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_24 = 35;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_25 = 36;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_26 = 37;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_27 = 38;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_28 = 39;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_29 = 40;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_30 = 41;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_31 = 42;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_32 = 43;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_33 = 44;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_34 = 45;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_35 = 46;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_36 = 47;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_37 = 48;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_38 = 49;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_39 = 50;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_40 = 51;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_41 = 52;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_42 = 53;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_43 = 54;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_44 = 55;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_45 = 56;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_46 = 57;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_47 = 58;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_48 = 59;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_49 = 60;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_50 = 61;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_51 = 62;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_52 = 63;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_53 = 64;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_54 = 65;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_55 = 66;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_56 = 67;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_57 = 68;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_58 = 69;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_59 = 70;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_60 = 71;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_61 = 72;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_62 = 73;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_63 = 74;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_64 = 75;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_65 = 76;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_66 = 77;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_67 = 78;
/*  */
const int LANGUAGESFONTNEW_LANGUAGES_FONT_68 = 79;
#endif
