/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_CrossApp_IM_IM */

#ifndef _Included_com_CrossApp_IM_IM
#define _Included_com_CrossApp_IM_IM


class com_CrossApp_IM_IM
{
public:
    static void init_android(const char* userName, const char* passWord);
    static void logout_android();
};


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_CrossApp_IM_IM
 * Method:    getInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_CrossApp_IM_IM_getInt
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_CrossApp_IM_IM
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_CrossApp_IM_IM_getString
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_CrossApp_IM_IM
 * Method:    callAdd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_CrossApp_IM_IM_callAdd
  (JNIEnv *, jclass);

/*
 * Class:     com_CrossApp_IM_IM
 * Method:    callJudge
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_CrossApp_IM_IM_callJudge
  (JNIEnv *, jclass);
    

#ifdef __cplusplus
}

#endif

#endif
